<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocalSeeder extends Seeder
{
    public function run()
    {
        $locals = [
            ['city' => 'AN GIANG', 'district' => 'An Phú'],
            ['city' => 'AN GIANG', 'district' => 'Châu Đốc'],
            ['city' => 'AN GIANG', 'district' => 'Chợ Mới'],
            ['city' => 'AN GIANG', 'district' => 'Châu Phú'],
            ['city' => 'AN GIANG', 'district' => 'Châu Thành'],
            ['city' => 'AN GIANG', 'district' => 'Long xuyên'],
            ['city' => 'AN GIANG', 'district' => 'Phú Tân'],
            ['city' => 'AN GIANG', 'district' => 'Tịnh Biên'],
            ['city' => 'AN GIANG', 'district' => 'Tân Châu'],
            ['city' => 'AN GIANG', 'district' => 'Thoại Sơn'],
            ['city' => 'AN GIANG', 'district' => 'Tri Tôn'],
            ['city' => 'BẮC KẠN', 'district' => 'Ba Bể'],
            ['city' => 'BẮC KẠN', 'district' => 'Bắc Kạn'],
            ['city' => 'BẮC KẠN', 'district' => 'Bạch Thông'],
            ['city' => 'BẮC KẠN', 'district' => 'Chợ Đồn'],
            ['city' => 'BẮC KẠN', 'district' => 'Chợ Mới'],
            ['city' => 'BẮC KẠN', 'district' => 'Na Rì'],
            ['city' => 'BẮC KẠN', 'district' => 'Ngân Sơn'],
            ['city' => 'BẮC KẠN', 'district' => 'Pác Nặm'],
            ['city' => 'BÌNH DƯƠNG', 'district' => 'Bàu Bàng'],
            ['city' => 'BÌNH DƯƠNG', 'district' => 'TX. Bến Cát'],
            ['city' => 'BÌNH DƯƠNG', 'district' => 'Bắc Tân Uyên'],
            ['city' => 'BÌNH DƯƠNG', 'district' => 'Dĩ An'],
            ['city' => 'BÌNH DƯƠNG', 'district' => 'Thủ Dầu Một'],
            ['city' => 'BÌNH DƯƠNG', 'district' => 'Dầu Tiếng'],
            ['city' => 'BÌNH DƯƠNG', 'district' => 'Phú Giáo'],
            ['city' => 'BÌNH DƯƠNG', 'district' => 'Thuận An'],
            ['city' => 'BÌNH DƯƠNG', 'district' => 'TX. Tân Uyên'],
            ['city' => 'BÌNH ĐỊNH', 'district' => 'An Lão'],
            ['city' => 'BÌNH ĐỊNH', 'district' => 'An Nhơn'],
            ['city' => 'BÌNH ĐỊNH', 'district' => 'Hoài Ân'],
            ['city' => 'BÌNH ĐỊNH', 'district' => 'Hoài Nhơn'],
            ['city' => 'BÌNH ĐỊNH', 'district' => 'Phù Cát'],
            ['city' => 'BÌNH ĐỊNH', 'district' => 'Phù Mỹ'],
            ['city' => 'BÌNH ĐỊNH', 'district' => 'Quy Nhơn'],
            ['city' => 'BÌNH ĐỊNH', 'district' => 'Tuy Phước'],
            ['city' => 'BÌNH ĐỊNH', 'district' => 'Tây Sơn'],
            ['city' => 'BÌNH ĐỊNH', 'district' => 'Vân Canh'],
            ['city' => 'BÌNH ĐỊNH', 'district' => 'Vĩnh Thạnh'],
            ['city' => 'BẮC GIANG', 'district' => 'Bắc Giang'],
            ['city' => 'BẮC GIANG', 'district' => 'Hiệp Hòa'],
            ['city' => 'BẮC GIANG', 'district' => 'Lạng Giang'],
            ['city' => 'BẮC GIANG', 'district' => 'Lục Nam'],
            ['city' => 'BẮC GIANG', 'district' => 'Lục Ngạn'],
            ['city' => 'BẮC GIANG', 'district' => 'Sơn Động'],
            ['city' => 'BẮC GIANG', 'district' => 'Tân Yên'],
            ['city' => 'BẮC GIANG', 'district' => 'Việt Yên'],
            ['city' => 'BẮC GIANG', 'district' => 'Yên Dũng'],
            ['city' => 'BẮC GIANG', 'district' => 'Yên Thế'],
            ['city' => 'BẠC LIÊU', 'district' => 'Bạc Liêu'],
            ['city' => 'BẠC LIÊU', 'district' => 'Đông Hải'],
            ['city' => 'BẠC LIÊU', 'district' => 'Giá Rai'],
            ['city' => 'BẠC LIÊU', 'district' => 'Hòa Bình'],
            ['city' => 'BẠC LIÊU', 'district' => 'Hồng Dân'],
            ['city' => 'BẠC LIÊU', 'district' => 'Phước Long'],
            ['city' => 'BẠC LIÊU', 'district' => 'Vĩnh Lợi'],
            ['city' => 'BẮC NINH', 'district' => 'Bắc Ninh'],
            ['city' => 'BẮC NINH', 'district' => 'Gia Bình'],
            ['city' => 'BẮC NINH', 'district' => 'Lương Tài'],
            ['city' => 'BẮC NINH', 'district' => 'Quế Võ'],
            ['city' => 'BẮC NINH', 'district' => 'Tiên Du'],
            ['city' => 'BẮC NINH', 'district' => 'Từ Sơn'],
            ['city' => 'BẮC NINH', 'district' => 'Thuận Thành'],
            ['city' => 'BẮC NINH', 'district' => 'Yên Phong'],
            ['city' => 'BÌNH PHƯỚC', 'district' => 'Bù Đăng'],
            ['city' => 'BÌNH PHƯỚC', 'district' => 'Bù Đốp'],
            ['city' => 'BÌNH PHƯỚC', 'district' => 'Bình Long'],
            ['city' => 'BÌNH PHƯỚC', 'district' => 'Chơn Thành'],
            ['city' => 'BÌNH PHƯỚC', 'district' => 'Đồng Phú'],
            ['city' => 'BÌNH PHƯỚC', 'district' => 'Đồng Xoài'],
            ['city' => 'BÌNH PHƯỚC', 'district' => 'Bù Gia Mập'],
            ['city' => 'BÌNH PHƯỚC', 'district' => 'Hớn Quản'],
            ['city' => 'BÌNH PHƯỚC', 'district' => 'Lộc Ninh'],
            ['city' => 'BÌNH PHƯỚC', 'district' => 'Phước Long'],
            ['city' => 'BÌNH PHƯỚC', 'district' => 'Phú Riềng'],
            ['city' => 'BẾN TRE', 'district' => 'Bình Đại'],
            ['city' => 'BẾN TRE', 'district' => 'TP. Bến Tre'],
            ['city' => 'BẾN TRE', 'district' => 'Ba Tri'],
            ['city' => 'BẾN TRE', 'district' => 'Mỏ Cày Bắc'],
            ['city' => 'BẾN TRE', 'district' => 'Chợ Lách'],
            ['city' => 'BẾN TRE', 'district' => 'Mỏ Cày Nam'],
            ['city' => 'BẾN TRE', 'district' => 'Châu Thành'],
            ['city' => 'BẾN TRE', 'district' => 'Giồng Trôm'],
            ['city' => 'BẾN TRE', 'district' => 'Thạnh Phú'],
            ['city' => 'BÌNH THUẬN', 'district' => 'Bắc Bình'],
            ['city' => 'BÌNH THUẬN', 'district' => 'Đức Linh'],
            ['city' => 'BÌNH THUẬN', 'district' => 'Hàm Tân'],
            ['city' => 'BÌNH THUẬN', 'district' => 'La Gi'],
            ['city' => 'BÌNH THUẬN', 'district' => 'Phú Quý'],
            ['city' => 'BÌNH THUẬN', 'district' => 'Phan Thiết'],
            ['city' => 'BÌNH THUẬN', 'district' => 'Hàm Thuận Bắc'],
            ['city' => 'BÌNH THUẬN', 'district' => 'Tánh Linh'],
            ['city' => 'BÌNH THUẬN', 'district' => 'Hàm Thuận Nam'],
            ['city' => 'BÌNH THUẬN', 'district' => 'Tuy Phong'],
            ['city' => 'CAO BẰNG', 'district' => 'Bảo Lạc'],
            ['city' => 'CAO BẰNG', 'district' => 'Bảo Lâm'],
            ['city' => 'CAO BẰNG', 'district' => 'Cao Bằng'],
            ['city' => 'CAO BẰNG', 'district' => 'Hòa An'],
            ['city' => 'CAO BẰNG', 'district' => 'Hạ Lang'],
            ['city' => 'CAO BẰNG', 'district' => 'Hà Quảng'],
            ['city' => 'CAO BẰNG', 'district' => 'Nguyên Bình'],
            ['city' => 'CAO BẰNG', 'district' => 'Quảng Hòa'],
            ['city' => 'CAO BẰNG', 'district' => 'Thạch An'],
            ['city' => 'CAO BẰNG', 'district' => 'Trùng Khánh'],
            ['city' => 'CÀ MAU', 'district' => 'Cà Mau'],
            ['city' => 'CÀ MAU', 'district' => 'Cái Nước'],
            ['city' => 'CÀ MAU', 'district' => 'Đầm Dơi'],
            ['city' => 'CÀ MAU', 'district' => 'Năm Căn'],
            ['city' => 'CÀ MAU', 'district' => 'Ngọc Hiển'],
            ['city' => 'CÀ MAU', 'district' => 'Phú Tân'],
            ['city' => 'CÀ MAU', 'district' => 'Thới Bình'],
            ['city' => 'CÀ MAU', 'district' => 'U Minh'],
            ['city' => 'CÀ MAU', 'district' => 'Trần Văn Thời'],
            ['city' => 'CẦN THƠ', 'district' => 'Bình Thủy'],
            ['city' => 'CẦN THƠ', 'district' => 'Cờ Đỏ'],
            ['city' => 'CẦN THƠ', 'district' => 'Cái Răng'],
            ['city' => 'CẦN THƠ', 'district' => 'Ninh Kiều'],
            ['city' => 'CẦN THƠ', 'district' => 'Ô Môn'],
            ['city' => 'CẦN THƠ', 'district' => 'Phong Điền'],
            ['city' => 'CẦN THƠ', 'district' => 'Thới Lai'],
            ['city' => 'CẦN THƠ', 'district' => 'Thốt Nốt'],
            ['city' => 'CẦN THƠ', 'district' => 'Vĩnh Thạnh'],
            ['city' => 'BẾN TRE', 'district' => 'Nậm Pồ'],
            ['city' => 'ĐIỆN BIÊN', 'district' => 'Điện Biên Đông'],
            ['city' => 'ĐIỆN BIÊN', 'district' => 'Điện Biên Phủ'],
            ['city' => 'ĐIỆN BIÊN', 'district' => 'Điện Biên'],
            ['city' => 'ĐIỆN BIÊN', 'district' => 'Mường Ảng'],
            ['city' => 'ĐIỆN BIÊN', 'district' => 'Mường Chà'],
            ['city' => 'ĐIỆN BIÊN', 'district' => 'Mường Lay'],
            ['city' => 'ĐIỆN BIÊN', 'district' => 'Mường Nhé'],
            ['city' => 'ĐIỆN BIÊN', 'district' => 'Nậm Pồ'],
            ['city' => 'ĐIỆN BIÊN', 'district' => 'Tủa Chùa'],
            ['city' => 'ĐIỆN BIÊN', 'district' => 'Tuần Giáo'],
            ['city' => 'ĐẮK NÔNG', 'district' => 'Cư Jút'],
            ['city' => 'ĐẮK NÔNG', 'district' => 'Đắk Glong'],
            ['city' => 'ĐẮK NÔNG', 'district' => 'Đắk Mil'],
            ['city' => 'ĐẮK NÔNG', 'district' => 'Đắk R&quot;Lấp'],
            ['city' => 'ĐẮK NÔNG', 'district' => 'Đắk Song'],
            ['city' => 'ĐẮK NÔNG', 'district' => 'Gia Nghĩa'],
            ['city' => 'ĐẮK NÔNG', 'district' => 'Krông Nô'],
            ['city' => 'ĐẮK NÔNG', 'district' => 'Tuy Đức'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Buôn Đôn'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Buôn Hồ'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Cư Kuin'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Cư M&quot;gar'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Ea H&quot;Leo'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Ea Kar'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Ea Súp'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Krông Ana'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Krông Bông'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Krông Buk'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Krông Năng'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Krông Pắc'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Lăk'],
            ['city' => 'ĐẮK LẮK', 'district' => 'M&quot;Đrăk'],
            ['city' => 'ĐẮK LẮK', 'district' => 'Buôn Ma Thuột'],
            ['city' => 'ĐÀ NẴNG', 'district' => 'Cẩm Lệ'],
            ['city' => 'ĐÀ NẴNG', 'district' => 'Hải Châu'],
            ['city' => 'ĐÀ NẴNG', 'district' => 'Hoàng Sa'],
            ['city' => 'ĐÀ NẴNG', 'district' => 'Ngũ Hành Sơn'],
            ['city' => 'ĐÀ NẴNG', 'district' => 'Hòa Vang'],
            ['city' => 'ĐÀ NẴNG', 'district' => 'Liên Chiểu'],
            ['city' => 'ĐÀ NẴNG', 'district' => 'Sơn Trà'],
            ['city' => 'ĐÀ NẴNG', 'district' => 'Thanh Khê'],
            ['city' => 'ĐỒNG NAI', 'district' => 'Biên Hòa'],
            ['city' => 'ĐỒNG NAI', 'district' => 'Cẩm Mỹ'],
            ['city' => 'ĐỒNG NAI', 'district' => 'Định Quán'],
            ['city' => 'ĐỒNG NAI', 'district' => 'Long Khánh'],
            ['city' => 'ĐỒNG NAI', 'district' => 'Long Thành'],
            ['city' => 'ĐỒNG NAI', 'district' => 'Nhơn Trạch'],
            ['city' => 'ĐỒNG NAI', 'district' => 'Trảng Bom'],
            ['city' => 'ĐỒNG NAI', 'district' => 'Thống Nhất'],
            ['city' => 'ĐỒNG NAI', 'district' => 'Tân phú'],
            ['city' => 'ĐỒNG NAI', 'district' => 'Vĩnh Cửu'],
            ['city' => 'ĐỒNG NAI', 'district' => 'Xuân Lộc'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'TP. Cao Lãnh'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'Cao Lãnh'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'Châu Thành'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'TP. Hồng Ngự'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'Hồng Ngự'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'Lai Vung'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'Lấp Vò'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'Sa Đéc'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'Thanh Bình'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'Tân Hồng'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'Tháp Mười'],
            ['city' => 'ĐỒNG THÁP', 'district' => 'Tam Nông'],
            ['city' => 'GIA LAI', 'district' => 'An Khê'],
            ['city' => 'GIA LAI', 'district' => 'Ayun Pa'],
            ['city' => 'GIA LAI', 'district' => 'Chư Prông'],
            ['city' => 'GIA LAI', 'district' => 'Chư Păh'],
            ['city' => 'GIA LAI', 'district' => 'Chư Sê'],
            ['city' => 'GIA LAI', 'district' => 'Chư Pưh'],
            ['city' => 'GIA LAI', 'district' => 'Đức Cơ'],
            ['city' => 'GIA LAI', 'district' => 'Đắk Đoa'],
            ['city' => 'GIA LAI', 'district' => 'Đắk Pơ'],
            ['city' => 'GIA LAI', 'district' => 'Ia Grai'],
            ['city' => 'GIA LAI', 'district' => 'Ia Pa'],
            ['city' => 'GIA LAI', 'district' => 'KBang'],
            ['city' => 'GIA LAI', 'district' => 'Kông Chro'],
            ['city' => 'GIA LAI', 'district' => 'Krông Pa'],
            ['city' => 'GIA LAI', 'district' => 'Mang Yang'],
            ['city' => 'GIA LAI', 'district' => 'Pleiku'],
            ['city' => 'GIA LAI', 'district' => 'Phú Thiện'],
            ['city' => 'HÒA BÌNH', 'district' => 'Cao Phong'],
            ['city' => 'HÒA BÌNH', 'district' => 'Đà Bắc'],
            ['city' => 'HÒA BÌNH', 'district' => 'Hòa Bình'],
            ['city' => 'HÒA BÌNH', 'district' => 'Kim Bôi'],
            ['city' => 'HÒA BÌNH', 'district' => 'Lương Sơn'],
            ['city' => 'HÒA BÌNH', 'district' => 'Lạc Sơn'],
            ['city' => 'HÒA BÌNH', 'district' => 'Lạc Thủy'],
            ['city' => 'HÒA BÌNH', 'district' => 'Mai Châu'],
            ['city' => 'HÒA BÌNH', 'district' => 'Tân Lạc'],
            ['city' => 'HÒA BÌNH', 'district' => 'Yên Thủy'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Quận 1'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Quận 3'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Quận 4'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Quận 5'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Quận 6'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Quận 7'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Quận 8'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Quận 10'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Quận 11'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Quận 12'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Bình Chánh'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Bình Thạnh'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Bình Tân'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Củ Chi'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Cần Giờ'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Gò Vấp'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Hóc Môn'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Nhà Bè'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Phú Nhuận'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Tân Bình'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'TP. Thủ Đức'],
            ['city' => 'HỒ CHÍ MINH', 'district' => 'Tân Phú'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Bình Giang'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Cẩm Giàng'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Chí Linh'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Gia Lộc'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Hải Dương'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Kinh Môn'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Kim Thành'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Ninh Giang'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Nam Sách'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Thanh Hà'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Tứ Kỳ'],
            ['city' => 'HẢI DƯƠNG', 'district' => 'Thanh Miện'],
            ['city' => 'HÀ GIANG', 'district' => 'Bắc Mê'],
            ['city' => 'HÀ GIANG', 'district' => 'Bắc Quang'],
            ['city' => 'HÀ GIANG', 'district' => 'Đồng Văn'],
            ['city' => 'HÀ GIANG', 'district' => 'Hà Giang'],
            ['city' => 'HÀ GIANG', 'district' => 'Mèo Vạc'],
            ['city' => 'HÀ GIANG', 'district' => 'Quản Bạ'],
            ['city' => 'HÀ GIANG', 'district' => 'Quang Bình'],
            ['city' => 'HÀ GIANG', 'district' => 'Hoàng Su Phì'],
            ['city' => 'HÀ GIANG', 'district' => 'Vị Xuyên'],
            ['city' => 'HÀ GIANG', 'district' => 'Xín Mần'],
            ['city' => 'HÀ GIANG', 'district' => 'Yên Minh'],
            ['city' => 'HÀ NỘI', 'district' => 'Ba Đình'],
            ['city' => 'HÀ NỘI', 'district' => 'Bắc Từ Liêm'],
            ['city' => 'HÀ NỘI', 'district' => 'Hai Bà Trưng'],
            ['city' => 'HÀ NỘI', 'district' => 'Ba Vì'],
            ['city' => 'HÀ NỘI', 'district' => 'Cầu Giấy'],
            ['city' => 'HÀ NỘI', 'district' => 'Chương Mỹ'],
            ['city' => 'HÀ NỘI', 'district' => 'Đông Anh'],
            ['city' => 'HÀ NỘI', 'district' => 'Đống Đa'],
            ['city' => 'HÀ NỘI', 'district' => 'Đan Phượng'],
            ['city' => 'HÀ NỘI', 'district' => 'Gia Lâm'],
            ['city' => 'HÀ NỘI', 'district' => 'Hoài Đức'],
            ['city' => 'HÀ NỘI', 'district' => 'Hà Đông'],
            ['city' => 'HÀ NỘI', 'district' => 'Hoàn Kiếm'],
            ['city' => 'HÀ NỘI', 'district' => 'Hoàng Mai'],
            ['city' => 'HÀ NỘI', 'district' => 'Long Biên'],
            ['city' => 'HÀ NỘI', 'district' => 'Mỹ Đức'],
            ['city' => 'HÀ NỘI', 'district' => 'Mê Linh'],
            ['city' => 'HÀ NỘI', 'district' => 'Nam Từ Liêm'],
            ['city' => 'HÀ NỘI', 'district' => 'Phúc Thọ'],
            ['city' => 'HÀ NỘI', 'district' => 'Phú Xuyên'],
            ['city' => 'HÀ NỘI', 'district' => 'Quốc Oai'],
            ['city' => 'HÀ NỘI', 'district' => 'Sóc Sơn'],
            ['city' => 'HÀ NỘI', 'district' => 'TX. Sơn Tây'],
            ['city' => 'HÀ NỘI', 'district' => 'Tây Hồ'],
            ['city' => 'HÀ NỘI', 'district' => 'Thanh Oai'],
            ['city' => 'HÀ NỘI', 'district' => 'Thanh Trì'],
            ['city' => 'HÀ NỘI', 'district' => 'Thường Tín'],
            ['city' => 'HÀ NỘI', 'district' => 'Thạch Thất'],
            ['city' => 'HÀ NỘI', 'district' => 'Thanh Xuân'],
            ['city' => 'HÀ NỘI', 'district' => 'Ứng Hòa'],
            ['city' => 'HÀ NAM', 'district' => 'Bình Lục'],
            ['city' => 'HÀ NAM', 'district' => 'Duy Tiên'],
            ['city' => 'HÀ NAM', 'district' => 'Kim Bảng'],
            ['city' => 'HÀ NAM', 'district' => 'Lý Nhân'],
            ['city' => 'HÀ NAM', 'district' => 'Phủ Lý'],
            ['city' => 'HÀ NAM', 'district' => 'Thanh Liêm'],
            ['city' => 'HẢI PHÒNG', 'district' => 'An Dương'],
            ['city' => 'HẢI PHÒNG', 'district' => 'An Lão'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Cát Hải'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Dương Kinh'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Đồ Sơn'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Hải An'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Hồng Bàng'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Kiến An'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Kiến Thụy'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Lê Chân'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Bạch Long Vĩ'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Ngô Quyền'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Tiên Lãng'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Thủy Nguyên'],
            ['city' => 'HẢI PHÒNG', 'district' => 'Vĩnh Bảo'],
            ['city' => 'HÀ TĨNH', 'district' => 'Can Lộc'],
            ['city' => 'HÀ TĨNH', 'district' => 'Cẩm Xuyên'],
            ['city' => 'HÀ TĨNH', 'district' => 'Đức Thọ'],
            ['city' => 'HÀ TĨNH', 'district' => 'Hương Khê'],
            ['city' => 'HÀ TĨNH', 'district' => 'Hồng Lĩnh'],
            ['city' => 'HÀ TĨNH', 'district' => 'Hương Sơn'],
            ['city' => 'HÀ TĨNH', 'district' => 'TP. Hà Tĩnh'],
            ['city' => 'HÀ TĨNH', 'district' => 'Kỳ Anh'],
            ['city' => 'HÀ TĨNH', 'district' => 'TX. Kỳ Anh'],
            ['city' => 'HÀ TĨNH', 'district' => 'Lộc Hà'],
            ['city' => 'HÀ TĨNH', 'district' => 'Nghi Xuân'],
            ['city' => 'HÀ TĨNH', 'district' => 'Thạch Hà'],
            ['city' => 'HÀ TĨNH', 'district' => 'Vũ Quang'],
            ['city' => 'THỪA THIÊN HUẾ', 'district' => 'A Lưới'],
            ['city' => 'THỪA THIÊN HUẾ', 'district' => 'Hương Trà'],
            ['city' => 'THỪA THIÊN HUẾ', 'district' => 'TX. Hương Thủy'],
            ['city' => 'THỪA THIÊN HUẾ', 'district' => 'TP. Huế'],
            ['city' => 'THỪA THIÊN HUẾ', 'district' => 'Nam Đông'],
            ['city' => 'THỪA THIÊN HUẾ', 'district' => 'Phong Điền'],
            ['city' => 'THỪA THIÊN HUẾ', 'district' => 'Phú Lộc'],
            ['city' => 'THỪA THIÊN HUẾ', 'district' => 'Phú Vang'],
            ['city' => 'THỪA THIÊN HUẾ', 'district' => 'Quảng Điền'],
            ['city' => 'HẬU GIANG', 'district' => 'Châu Thành'],
            ['city' => 'HẬU GIANG', 'district' => 'Long Mỹ'],
            ['city' => 'HẬU GIANG', 'district' => 'TX. Long Mỹ'],
            ['city' => 'HẬU GIANG', 'district' => 'Ngã Bảy'],
            ['city' => 'HẬU GIANG', 'district' => 'Phụng Hiệp'],
            ['city' => 'HẬU GIANG', 'district' => 'Châu Thành A'],
            ['city' => 'HẬU GIANG', 'district' => 'Vị Thanh'],
            ['city' => 'HẬU GIANG', 'district' => 'Vị Thủy'],
            ['city' => 'HƯNG YÊN', 'district' => 'Ân Thi'],
            ['city' => 'HƯNG YÊN', 'district' => 'TP. Hưng Yên'],
            ['city' => 'HƯNG YÊN', 'district' => 'Khoái Châu'],
            ['city' => 'HƯNG YÊN', 'district' => 'Kim Động'],
            ['city' => 'HƯNG YÊN', 'district' => 'Mỹ Hào'],
            ['city' => 'HƯNG YÊN', 'district' => 'Phù Cừ'],
            ['city' => 'HƯNG YÊN', 'district' => 'Tiên Lữ'],
            ['city' => 'HƯNG YÊN', 'district' => 'Văn Giang'],
            ['city' => 'HƯNG YÊN', 'district' => 'Văn Lâm'],
            ['city' => 'HƯNG YÊN', 'district' => 'Yên Mỹ'],
            ['city' => 'KIÊN GIANG', 'district' => 'An Biên'],
            ['city' => 'KIÊN GIANG', 'district' => 'An Minh'],
            ['city' => 'KIÊN GIANG', 'district' => 'Châu Thành'],
            ['city' => 'KIÊN GIANG', 'district' => 'Gò Quao'],
            ['city' => 'KIÊN GIANG', 'district' => 'Giồng Riềng'],
            ['city' => 'KIÊN GIANG', 'district' => 'Giang Thành'],
            ['city' => 'KIÊN GIANG', 'district' => 'Hòn Đất'],
            ['city' => 'KIÊN GIANG', 'district' => 'Hà Tiên'],
            ['city' => 'KIÊN GIANG', 'district' => 'Kiên Hải'],
            ['city' => 'KIÊN GIANG', 'district' => 'Kiên Lương'],
            ['city' => 'KIÊN GIANG', 'district' => 'U Minh Thượng'],
            ['city' => 'KIÊN GIANG', 'district' => 'Phú Quốc'],
            ['city' => 'KIÊN GIANG', 'district' => 'Rạch Giá'],
            ['city' => 'KIÊN GIANG', 'district' => 'Tân Hiệp'],
            ['city' => 'KIÊN GIANG', 'district' => 'Vĩnh Thuận'],
            ['city' => 'KHÁNH HÒA', 'district' => 'Cam Lâm'],
            ['city' => 'KHÁNH HÒA', 'district' => 'TP. Cam Ranh'],
            ['city' => 'KHÁNH HÒA', 'district' => 'Diên Khánh'],
            ['city' => 'KHÁNH HÒA', 'district' => 'Khánh Sơn'],
            ['city' => 'KHÁNH HÒA', 'district' => 'Khánh Vĩnh'],
            ['city' => 'KHÁNH HÒA', 'district' => 'TX. Ninh Hòa'],
            ['city' => 'KHÁNH HÒA', 'district' => 'TP. Nha Trang'],
            ['city' => 'KHÁNH HÒA', 'district' => 'Trường Sa'],
            ['city' => 'KHÁNH HÒA', 'district' => 'Vạn Ninh'],
            ['city' => 'KON TUM', 'district' => 'Đắk Glei'],
            ['city' => 'KON TUM', 'district' => 'Đắk Hà'],
            ['city' => 'KON TUM', 'district' => 'Đăk Tô'],
            ['city' => 'KON TUM', 'district' => 'Ia H&quot; Drai'],
            ['city' => 'KON TUM', 'district' => 'Kon PLông'],
            ['city' => 'KON TUM', 'district' => 'Kon Rẫy'],
            ['city' => 'KON TUM', 'district' => 'Kon Tum'],
            ['city' => 'KON TUM', 'district' => 'Tu Mơ Rông'],
            ['city' => 'KON TUM', 'district' => 'Ngọc Hồi'],
            ['city' => 'KON TUM', 'district' => 'Sa Thầy'],
            ['city' => 'LONG AN', 'district' => 'Bến Lức'],
            ['city' => 'LONG AN', 'district' => 'Cần Đước'],
            ['city' => 'LONG AN', 'district' => 'Cần Giuộc'],
            ['city' => 'LONG AN', 'district' => 'Châu Thành'],
            ['city' => 'LONG AN', 'district' => 'Đức Hòa'],
            ['city' => 'LONG AN', 'district' => 'Đức Huệ'],
            ['city' => 'LONG AN', 'district' => 'TX. Kiến Tường'],
            ['city' => 'LONG AN', 'district' => 'Mộc Hóa'],
            ['city' => 'LONG AN', 'district' => 'Tân An'],
            ['city' => 'LONG AN', 'district' => 'Thạnh Hóa'],
            ['city' => 'LONG AN', 'district' => 'Tân Hưng'],
            ['city' => 'LONG AN', 'district' => 'Thủ Thừa'],
            ['city' => 'LONG AN', 'district' => 'Tân Thạnh'],
            ['city' => 'LONG AN', 'district' => 'Tân Trụ'],
            ['city' => 'LONG AN', 'district' => 'Vĩnh Hưng'],
            ['city' => 'LÀO CAI', 'district' => 'Bắc Hà'],
            ['city' => 'LÀO CAI', 'district' => 'Bảo Thắng'],
            ['city' => 'LÀO CAI', 'district' => 'Bát Xát'],
            ['city' => 'LÀO CAI', 'district' => 'Bảo Yên'],
            ['city' => 'LÀO CAI', 'district' => 'Lào Cai'],
            ['city' => 'LÀO CAI', 'district' => 'Si Ma Cai'],
            ['city' => 'LÀO CAI', 'district' => 'Mường Khương'],
            ['city' => 'LÀO CAI', 'district' => 'Sa Pa'],
            ['city' => 'LÀO CAI', 'district' => 'Văn Bàn'],
            ['city' => 'LAI CHÂU', 'district' => 'Lai Châu'],
            ['city' => 'LAI CHÂU', 'district' => 'Mường Tè'],
            ['city' => 'LAI CHÂU', 'district' => 'Nậm Nhùn'],
            ['city' => 'LAI CHÂU', 'district' => 'Phong Thổ'],
            ['city' => 'LAI CHÂU', 'district' => 'Sìn Hồ'],
            ['city' => 'LAI CHÂU', 'district' => 'Tam Đường'],
            ['city' => 'LAI CHÂU', 'district' => 'Than Uyên'],
            ['city' => 'LAI CHÂU', 'district' => 'Tân Uyên'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Bảo Lộc'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Bảo Lâm'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Cát Tiên'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Đơn Dương'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Đạ Huoai'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Di Linh'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Đà Lạt'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Đam Rông'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Đức Trọng'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Đạ Tẻh'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Lạc Dương'],
            ['city' => 'LÂM ĐỒNG', 'district' => 'Lâm Hà'],
            ['city' => 'LẠNG SƠN', 'district' => 'Bình Gia'],
            ['city' => 'LẠNG SƠN', 'district' => 'Bắc Sơn'],
            ['city' => 'LẠNG SƠN', 'district' => 'Cao Lộc'],
            ['city' => 'LẠNG SƠN', 'district' => 'Chi Lăng'],
            ['city' => 'LẠNG SƠN', 'district' => 'Đình Lập'],
            ['city' => 'LẠNG SƠN', 'district' => 'Hữu Lũng'],
            ['city' => 'LẠNG SƠN', 'district' => 'Lộc Bình'],
            ['city' => 'LẠNG SƠN', 'district' => 'Lạng Sơn'],
            ['city' => 'LẠNG SƠN', 'district' => 'Tràng Định'],
            ['city' => 'LẠNG SƠN', 'district' => 'Văn Lãng'],
            ['city' => 'LẠNG SƠN', 'district' => 'Văn Quan'],
            ['city' => 'NGHỆ AN', 'district' => 'Anh Sơn'],
            ['city' => 'NGHỆ AN', 'district' => 'Con Cuông'],
            ['city' => 'NGHỆ AN', 'district' => 'Cửa Lò'],
            ['city' => 'NGHỆ AN', 'district' => 'Diễn Châu'],
            ['city' => 'NGHỆ AN', 'district' => 'Đô Lương'],
            ['city' => 'NGHỆ AN', 'district' => 'TX. Hoàng Mai'],
            ['city' => 'NGHỆ AN', 'district' => 'Hưng Nguyên'],
            ['city' => 'NGHỆ AN', 'district' => 'Kỳ Sơn'],
            ['city' => 'NGHỆ AN', 'district' => 'Nghĩa Đàn'],
            ['city' => 'NGHỆ AN', 'district' => 'Nam Đàn'],
            ['city' => 'NGHỆ AN', 'district' => 'Nghi Lộc'],
            ['city' => 'NGHỆ AN', 'district' => 'Quỳ Châu'],
            ['city' => 'NGHỆ AN', 'district' => 'Quỳ Hợp'],
            ['city' => 'NGHỆ AN', 'district' => 'Quỳnh Lưu'],
            ['city' => 'NGHỆ AN', 'district' => 'Quế Phong'],
            ['city' => 'NGHỆ AN', 'district' => 'Thanh Chương'],
            ['city' => 'NGHỆ AN', 'district' => 'Tương Dương'],
            ['city' => 'NGHỆ AN', 'district' => 'Thái Hòa'],
            ['city' => 'NGHỆ AN', 'district' => 'Tân Kỳ'],
            ['city' => 'NGHỆ AN', 'district' => 'Vinh'],
            ['city' => 'NGHỆ AN', 'district' => 'Yên Thành'],
            ['city' => 'NINH BÌNH', 'district' => 'Gia Viễn'],
            ['city' => 'NINH BÌNH', 'district' => 'Hoa Lư'],
            ['city' => 'NINH BÌNH', 'district' => 'Kim Sơn'],
            ['city' => 'NINH BÌNH', 'district' => 'Ninh Bình'],
            ['city' => 'NINH BÌNH', 'district' => 'Nho Quan'],
            ['city' => 'NINH BÌNH', 'district' => 'Tam Điệp'],
            ['city' => 'NINH BÌNH', 'district' => 'Yên Khánh'],
            ['city' => 'NINH BÌNH', 'district' => 'Yên Mô'],
            ['city' => 'NAM ĐỊNH', 'district' => 'Giao Thủy'],
            ['city' => 'NAM ĐỊNH', 'district' => 'Hải Hậu'],
            ['city' => 'NAM ĐỊNH', 'district' => 'Mỹ Lộc'],
            ['city' => 'NAM ĐỊNH', 'district' => 'Nam Định'],
            ['city' => 'NAM ĐỊNH', 'district' => 'Nghĩa Hưng'],
            ['city' => 'NAM ĐỊNH', 'district' => 'Nam Trực'],
            ['city' => 'NAM ĐỊNH', 'district' => 'Trực Ninh'],
            ['city' => 'NAM ĐỊNH', 'district' => 'Vụ Bản'],
            ['city' => 'NAM ĐỊNH', 'district' => 'Xuân Trường'],
            ['city' => 'NAM ĐỊNH', 'district' => 'Ý Yên'],
            ['city' => 'NINH THUẬN', 'district' => 'Bác Ái'],
            ['city' => 'NINH THUẬN', 'district' => 'Ninh Hải'],
            ['city' => 'NINH THUẬN', 'district' => 'Ninh Phước'],
            ['city' => 'NINH THUẬN', 'district' => 'Ninh Sơn'],
            ['city' => 'NINH THUẬN', 'district' => 'Phan Rang-Tháp Chàm'],
            ['city' => 'NINH THUẬN', 'district' => 'Thuận Bắc'],
            ['city' => 'NINH THUẬN', 'district' => 'Thuận Nam'],
            ['city' => 'PHÚ THỌ', 'district' => 'Cẩm Khê'],
            ['city' => 'PHÚ THỌ', 'district' => 'Đoan Hùng'],
            ['city' => 'PHÚ THỌ', 'district' => 'Hạ Hòa'],
            ['city' => 'PHÚ THỌ', 'district' => 'Lâm Thao'],
            ['city' => 'PHÚ THỌ', 'district' => 'Phù Ninh'],
            ['city' => 'PHÚ THỌ', 'district' => 'Phú Thọ'],
            ['city' => 'PHÚ THỌ', 'district' => 'Thanh Ba'],
            ['city' => 'PHÚ THỌ', 'district' => 'Thanh Sơn'],
            ['city' => 'PHÚ THỌ', 'district' => 'Tam Nông'],
            ['city' => 'PHÚ THỌ', 'district' => 'Tân Sơn'],
            ['city' => 'PHÚ THỌ', 'district' => 'Thanh Thủy'],
            ['city' => 'PHÚ THỌ', 'district' => 'Việt Trì'],
            ['city' => 'PHÚ THỌ', 'district' => 'Yên Lập'],
            ['city' => 'PHÚ YÊN', 'district' => 'Đông Hòa'],
            ['city' => 'PHÚ YÊN', 'district' => 'Đồng Xuân'],
            ['city' => 'PHÚ YÊN', 'district' => 'Phú Hòa'],
            ['city' => 'PHÚ YÊN', 'district' => 'Sông Cầu'],
            ['city' => 'PHÚ YÊN', 'district' => 'Sơn Hòa'],
            ['city' => 'PHÚ YÊN', 'district' => 'Sông Hinh'],
            ['city' => 'PHÚ YÊN', 'district' => 'Tuy An'],
            ['city' => 'PHÚ YÊN', 'district' => 'Tây Hòa'],
            ['city' => 'PHÚ YÊN', 'district' => 'Tuy Hòa'],
            ['city' => 'QUẢNG BÌNH', 'district' => 'TX. Ba Đồn'],
            ['city' => 'QUẢNG BÌNH', 'district' => 'Bố Trạch'],
            ['city' => 'QUẢNG BÌNH', 'district' => 'Đồng Hới'],
            ['city' => 'QUẢNG BÌNH', 'district' => 'Lệ Thủy'],
            ['city' => 'QUẢNG BÌNH', 'district' => 'Minh Hóa'],
            ['city' => 'QUẢNG BÌNH', 'district' => 'Quảng Ninh'],
            ['city' => 'QUẢNG BÌNH', 'district' => 'Quảng Trạch'],
            ['city' => 'QUẢNG BÌNH', 'district' => 'Tuyên Hóa'],
            ['city' => 'QUẢNG NINH', 'district' => 'Ba Chẽ'],
            ['city' => 'QUẢNG NINH', 'district' => 'Bình Liêu'],
            ['city' => 'QUẢNG NINH', 'district' => 'Cẩm Phả'],
            ['city' => 'QUẢNG NINH', 'district' => 'Cô Tô'],
            ['city' => 'QUẢNG NINH', 'district' => 'Đầm Hà'],
            ['city' => 'QUẢNG NINH', 'district' => 'Đông Triều'],
            ['city' => 'QUẢNG NINH', 'district' => 'Hải Hà'],
            ['city' => 'QUẢNG NINH', 'district' => 'Hạ Long'],
            ['city' => 'QUẢNG NINH', 'district' => 'Móng Cái'],
            ['city' => 'QUẢNG NINH', 'district' => 'Quảng Yên'],
            ['city' => 'QUẢNG NINH', 'district' => 'Tiên Yên'],
            ['city' => 'QUẢNG NINH', 'district' => 'Uông Bí'],
            ['city' => 'QUẢNG NINH', 'district' => 'Vân Đồn'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Bình Sơn'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Ba Tơ'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Đức Phổ'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Lý Sơn'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Mộ Đức'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Minh Long'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Nghĩa Hành'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'TP. Quảng Ngãi'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Sơn Hà'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Sơn Tịnh'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Sơn Tây'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Trà Bồng'],
            ['city' => 'QUẢNG NGÃI', 'district' => 'Tư Nghĩa'],
            ['city' => 'QUẢNG NAM', 'district' => 'Bắc Trà My'],
            ['city' => 'QUẢNG NAM', 'district' => 'Điện Bàn'],
            ['city' => 'QUẢNG NAM', 'district' => 'Đông Giang'],
            ['city' => 'QUẢNG NAM', 'district' => 'Đại Lộc'],
            ['city' => 'QUẢNG NAM', 'district' => 'Duy Xuyên'],
            ['city' => 'QUẢNG NAM', 'district' => 'Hội An'],
            ['city' => 'QUẢNG NAM', 'district' => 'Hiệp Đức'],
            ['city' => 'QUẢNG NAM', 'district' => 'Nam Giang'],
            ['city' => 'QUẢNG NAM', 'district' => 'Nam Trà My'],
            ['city' => 'QUẢNG NAM', 'district' => 'Nông Sơn'],
            ['city' => 'QUẢNG NAM', 'district' => 'Núi Thành'],
            ['city' => 'QUẢNG NAM', 'district' => 'Phú Ninh'],
            ['city' => 'QUẢNG NAM', 'district' => 'Phước Sơn'],
            ['city' => 'QUẢNG NAM', 'district' => 'Quế Sơn'],
            ['city' => 'QUẢNG NAM', 'district' => 'Thăng Bình'],
            ['city' => 'QUẢNG NAM', 'district' => 'Tây Giang'],
            ['city' => 'QUẢNG NAM', 'district' => 'TP. Tam Kỳ'],
            ['city' => 'QUẢNG NAM', 'district' => 'Tiên Phước'],
            ['city' => 'QUẢNG TRỊ', 'district' => 'Cồn Cỏ'],
            ['city' => 'QUẢNG TRỊ', 'district' => 'Cam Lộ'],
            ['city' => 'QUẢNG TRỊ', 'district' => 'Đông Hà'],
            ['city' => 'QUẢNG TRỊ', 'district' => 'Đa KRông'],
            ['city' => 'QUẢNG TRỊ', 'district' => 'Gio Linh'],
            ['city' => 'QUẢNG TRỊ', 'district' => 'Hướng Hóa'],
            ['city' => 'QUẢNG TRỊ', 'district' => 'Hải Lăng'],
            ['city' => 'QUẢNG TRỊ', 'district' => 'Quảng Trị'],
            ['city' => 'QUẢNG TRỊ', 'district' => 'Triệu Phong'],
            ['city' => 'QUẢNG TRỊ', 'district' => 'Vĩnh Linh'],
            ['city' => 'SƠN LA', 'district' => 'Bắc Yên'],
            ['city' => 'SƠN LA', 'district' => 'Mộc Châu'],
            ['city' => 'SƠN LA', 'district' => 'Mường La'],
            ['city' => 'SƠN LA', 'district' => 'Mai Sơn'],
            ['city' => 'SƠN LA', 'district' => 'Phù Yên'],
            ['city' => 'SƠN LA', 'district' => 'Quỳnh Nhai'],
            ['city' => 'SƠN LA', 'district' => 'Sốp Cộp'],
            ['city' => 'SƠN LA', 'district' => 'Sơn La'],
            ['city' => 'SƠN LA', 'district' => 'Sông Mã'],
            ['city' => 'SƠN LA', 'district' => 'Thuận Châu'],
            ['city' => 'SƠN LA', 'district' => 'Vân Hồ'],
            ['city' => 'SƠN LA', 'district' => 'Yên Châu'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Châu Thành'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Kế Sách'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Cù Lao Dung'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Long Phú'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Mỹ Tú'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Mỹ Xuyên'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Ngã Năm'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Phụng Hiệp'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Sóc Trăng'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Trần Đề'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Thạnh Trị'],
            ['city' => 'SÓC TRĂNG', 'district' => 'Vĩnh Châu'],
            ['city' => 'THÁI BÌNH', 'district' => 'Đông Hưng'],
            ['city' => 'THÁI BÌNH', 'district' => 'Hưng Hà'],
            ['city' => 'THÁI BÌNH', 'district' => 'Kiến Xương'],
            ['city' => 'THÁI BÌNH', 'district' => 'Quỳnh Phụ'],
            ['city' => 'THÁI BÌNH', 'district' => 'Thái Bình'],
            ['city' => 'THÁI BÌNH', 'district' => 'Tiền Hải'],
            ['city' => 'THÁI BÌNH', 'district' => 'Thái Thụy'],
            ['city' => 'THÁI BÌNH', 'district' => 'Vũ Thư'],
            ['city' => 'TIỀN GIANG', 'district' => 'TX. Cai Lậy'],
            ['city' => 'TIỀN GIANG', 'district' => 'Cái Bè'],
            ['city' => 'TIỀN GIANG', 'district' => 'Gò Công Đông'],
            ['city' => 'TIỀN GIANG', 'district' => 'Chợ Gạo'],
            ['city' => 'TIỀN GIANG', 'district' => 'Cai Lậy'],
            ['city' => 'TIỀN GIANG', 'district' => 'Châu Thành'],
            ['city' => 'TIỀN GIANG', 'district' => 'Gò Công Tây'],
            ['city' => 'TIỀN GIANG', 'district' => 'Gò Công'],
            ['city' => 'TIỀN GIANG', 'district' => 'TP. Mỹ Tho'],
            ['city' => 'TIỀN GIANG', 'district' => 'Tân Phú Đông'],
            ['city' => 'TIỀN GIANG', 'district' => 'Tân Phước'],
            ['city' => 'THANH HÓA', 'district' => 'Bỉm Sơn'],
            ['city' => 'THANH HÓA', 'district' => 'Bá Thước'],
            ['city' => 'THANH HÓA', 'district' => 'Cẩm Thủy'],
            ['city' => 'THANH HÓA', 'district' => 'Đông Sơn'],
            ['city' => 'THANH HÓA', 'district' => 'Hoằng Hóa'],
            ['city' => 'THANH HÓA', 'district' => 'Hậu Lộc'],
            ['city' => 'THANH HÓA', 'district' => 'Hà Trung'],
            ['city' => 'THANH HÓA', 'district' => 'Lang Chánh'],
            ['city' => 'THANH HÓA', 'district' => 'Mường Lát'],
            ['city' => 'THANH HÓA', 'district' => 'Nông Cống'],
            ['city' => 'THANH HÓA', 'district' => 'TX. Nghi Sơn'],
            ['city' => 'THANH HÓA', 'district' => 'Ngọc Lặc'],
            ['city' => 'THANH HÓA', 'district' => 'Nga Sơn'],
            ['city' => 'THANH HÓA', 'district' => 'Như Thanh'],
            ['city' => 'THANH HÓA', 'district' => 'Như Xuân'],
            ['city' => 'THANH HÓA', 'district' => 'Quan Hóa'],
            ['city' => 'THANH HÓA', 'district' => 'Quan Sơn'],
            ['city' => 'THANH HÓA', 'district' => 'Quảng Xương'],
            ['city' => 'THANH HÓA', 'district' => 'Sầm Sơn'],
            ['city' => 'THANH HÓA', 'district' => 'Thường Xuân'],
            ['city' => 'THANH HÓA', 'district' => 'Thanh Hóa'],
            ['city' => 'THANH HÓA', 'district' => 'Triệu Sơn'],
            ['city' => 'THANH HÓA', 'district' => 'Thạch Thành'],
            ['city' => 'THANH HÓA', 'district' => 'Thiệu Hóa'],
            ['city' => 'THANH HÓA', 'district' => 'Thọ Xuân'],
            ['city' => 'THANH HÓA', 'district' => 'Vĩnh Lộc'],
            ['city' => 'THANH HÓA', 'district' => 'Yên Định'],
            ['city' => 'TÂY NINH', 'district' => 'Bến Cầu'],
            ['city' => 'TÂY NINH', 'district' => 'Châu Thành'],
            ['city' => 'TÂY NINH', 'district' => 'Gò Dầu'],
            ['city' => 'TÂY NINH', 'district' => 'TX. Hòa Thành'],
            ['city' => 'TÂY NINH', 'district' => 'Dương Minh Châu'],
            ['city' => 'TÂY NINH', 'district' => 'Trảng Bàng'],
            ['city' => 'TÂY NINH', 'district' => 'Tân Biên'],
            ['city' => 'TÂY NINH', 'district' => 'Tân Châu'],
            ['city' => 'TÂY NINH', 'district' => 'Tây Ninh'],
            ['city' => 'THÁI NGUYÊN', 'district' => 'Định Hóa'],
            ['city' => 'THÁI NGUYÊN', 'district' => 'Đồng Hỷ'],
            ['city' => 'THÁI NGUYÊN', 'district' => 'Đại Từ'],
            ['city' => 'THÁI NGUYÊN', 'district' => 'Phú Bình'],
            ['city' => 'THÁI NGUYÊN', 'district' => 'Phú Lương'],
            ['city' => 'THÁI NGUYÊN', 'district' => 'Phổ Yên'],
            ['city' => 'THÁI NGUYÊN', 'district' => 'Sông Công'],
            ['city' => 'THÁI NGUYÊN', 'district' => 'Thái Nguyên'],
            ['city' => 'THÁI NGUYÊN', 'district' => 'Võ Nhai'],
            ['city' => 'TUYÊN QUANG', 'district' => 'Chiêm Hóa'],
            ['city' => 'TUYÊN QUANG', 'district' => 'Hàm Yên'],
            ['city' => 'TUYÊN QUANG', 'district' => 'Lâm Bình'],
            ['city' => 'TUYÊN QUANG', 'district' => 'Na Hang'],
            ['city' => 'TUYÊN QUANG', 'district' => 'Sơn Dương'],
            ['city' => 'TUYÊN QUANG', 'district' => 'Tuyên Quang'],
            ['city' => 'TUYÊN QUANG', 'district' => 'Yên Sơn'],
            ['city' => 'TRÀ VINH', 'district' => 'Cầu Kè'],
            ['city' => 'TRÀ VINH', 'district' => 'Càng Long'],
            ['city' => 'TRÀ VINH', 'district' => 'Cầu Ngang'],
            ['city' => 'TRÀ VINH', 'district' => 'Châu Thành'],
            ['city' => 'TRÀ VINH', 'district' => 'Duyên Hải'],
            ['city' => 'TRÀ VINH', 'district' => 'TX. Duyên Hải'],
            ['city' => 'TRÀ VINH', 'district' => 'Tiểu Cần'],
            ['city' => 'TRÀ VINH', 'district' => 'Trà Cú'],
            ['city' => 'TRÀ VINH', 'district' => 'Trà Vinh'],
            ['city' => 'VĨNH LONG', 'district' => 'Bình Minh'],
            ['city' => 'VĨNH LONG', 'district' => 'Bình Tân'],
            ['city' => 'VĨNH LONG', 'district' => 'Long Hồ'],
            ['city' => 'VĨNH LONG', 'district' => 'Mang Thít'],
            ['city' => 'VĨNH LONG', 'district' => 'Tam Bình'],
            ['city' => 'VĨNH LONG', 'district' => 'Trà Ôn'],
            ['city' => 'VĨNH LONG', 'district' => 'Vĩnh Long'],
            ['city' => 'VĨNH LONG', 'district' => 'Vũng Liêm'],
            ['city' => 'VĨNH PHÚC', 'district' => 'Bình Xuyên'],
            ['city' => 'VĨNH PHÚC', 'district' => 'Lập Thạch'],
            ['city' => 'VĨNH PHÚC', 'district' => 'Phúc Yên'],
            ['city' => 'VĨNH PHÚC', 'district' => 'Sông Lô'],
            ['city' => 'VĨNH PHÚC', 'district' => 'Tam Dương'],
            ['city' => 'VĨNH PHÚC', 'district' => 'Tam Đảo'],
            ['city' => 'VĨNH PHÚC', 'district' => 'Vĩnh Tường'],
            ['city' => 'VĨNH PHÚC', 'district' => 'Vĩnh Yên'],
            ['city' => 'VĨNH PHÚC', 'district' => 'Yên Lạc'],
            ['city' => 'BÀ RỊA VŨNG TÀU', 'district' => 'TP. Bà Rịa'],
            ['city' => 'BÀ RỊA VŨNG TÀU', 'district' => 'Châu Đức'],
            ['city' => 'BÀ RỊA VŨNG TÀU', 'district' => 'Côn Đảo'],
            ['city' => 'BÀ RỊA VŨNG TÀU', 'district' => 'Đất Đỏ'],
            ['city' => 'BÀ RỊA VŨNG TÀU', 'district' => 'Long Điền'],
            ['city' => 'BÀ RỊA VŨNG TÀU', 'district' => 'TX. Phú Mỹ'],
            ['city' => 'BÀ RỊA VŨNG TÀU', 'district' => 'TP. Vũng Tàu'],
            ['city' => 'BÀ RỊA VŨNG TÀU', 'district' => 'Xuyên Mộc'],
            ['city' => 'YÊN BÁI', 'district' => 'Mù Cang Chải'],
            ['city' => 'YÊN BÁI', 'district' => 'Lục Yên'],
            ['city' => 'YÊN BÁI', 'district' => 'Nghĩa Lộ'],
            ['city' => 'YÊN BÁI', 'district' => 'Trạm Tấu'],
            ['city' => 'YÊN BÁI', 'district' => 'Trấn Yên'],
            ['city' => 'YÊN BÁI', 'district' => 'Văn Chấn'],
            ['city' => 'YÊN BÁI', 'district' => 'Văn Yên'],
            ['city' => 'YÊN BÁI', 'district' => 'Yên Bình'],
            ['city' => 'YÊN BÁI', 'district' => 'Yên Bái'],
        ];
        foreach ($locals as $local) {
            DB::table('locals')->insert($local);
        }
    }
}
